### ISSUE TITLE
Use appveyor to test windows compatibility

### ISSUE THREAD

**Issue by forresst** [nkbt/react-component-template#12]
Although I am not a specialist, the implementation of appveyor (or other) would test the Windows compatibility in the npm scripts.

What do you think about it ?

**Comment by nkbt** [comment]
Sounds interesting. I reckon that is another CI. Keen to make a PR with base config?

PS: exactly at current moment I am sitting behind Mac and PC, pushing from Mac and running scripts on PC. That is funny. Would be cool to have this automated.

**Comment by nkbt** [comment]
https://ci.appveyor.com/project/nkbt/react-component-template

**Comment by forresst** [comment]
As I said, I'm not a specialist, but I want to try. I read the doc, I make tests quickly and I try to do a PR.

**Comment by forresst** [comment]
First test : https://ci.appveyor.com/project/forresst/react-component-template/build/2

**Comment by nkbt** [comment]
:yum: nice

**Comment by nkbt** [comment]
Hi, @forresst since your build is working, you can do a PR and all extra configuration if needed I could add later. What do you reckon?

**Comment by iamstarkov** [comment]
sounds really good

**Comment by forresst** [comment]
Oooooops ! I forgot the subject.

I made some changes to be roughly equivalent to circleCI:
- only node.js 0.10.4
- Install npm release 3 : `npm -g install npm@3`
- I deleted 'npm run build'. It was launched twice!

Sorry for the delay

**Comment by nkbt** [comment]
@forresst no worries! Thank you a lot!
