### ISSUE TITLE
Use global Babel6 config when Isparta is updated

### ISSUE THREAD

**Issue by nkbt** [nkbt/react-component-template#15]
At the moment isparta uses babel@5, so global babel config cannot be used (babel@5 fails to run). So there are in-place babel configs. 

When isparta is updated (see https://github.com/douglasduteil/isparta/issues/81), remove in-place babel configs and use one global in package.json.

**Comment by iamstarkov** [comment]
i think isparta should delegate config resolving to babel

**Comment by nkbt** [comment]
Fixed by #33
