### ISSUE TITLE
Windows-compatible npm-scripts

### ISSUE THREAD

**Issue by nkbt** [nkbt/react-component-template#2]
Oh yeah... Apparently it is needed. Even for me. Sometimes. Did not want to take work mac with me on holidays and took SurfacePro instead. I know your pain now, windows-based devs.

Will do something similar to https://github.com/cloverfield-tools/cf-package/commit/16835f637e552ab97dc39c24845f5f463938597f

Thanks @forresst

**Comment by forresst** [comment]
Lol ! Good holidays

**Comment by forresst** [comment]
If you want, i will do the PR ?

**Comment by nkbt** [comment]
I definitely would not mind =). That would be awesome! Thank you

We also need rimraf here too.

**Comment by forresst** [comment]
I will do asap.

**Comment by nkbt** [comment]
\o/

**Comment by forresst** [comment]
I see that you were faster than me.
Sorry, I was not very available. But I would look with interest your PR. Because I am not a specialist of karma and coverage.

**Comment by nkbt** [comment]
@forresst yeah, sorry... had to do it since I need to publish some components and this was a blocker for me.
See #3 for changes. There are not that much actually, everything looks pretty simple.
